# Generated by Django 3.0.5 on 2020-04-25 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0003_auto_20200424_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcuser',
            old_name='useremail',
            new_name='email',
        ),
    ]
