# Generated by Django 3.0.5 on 2020-04-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0004_auto_20200425_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='registered_dttm',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록시간'),
        ),
    ]
