# Generated by Django 3.0.5 on 2020-04-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='registered_dttm',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록일자'),
        ),
    ]
